import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "./Toaster/sonner"

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Expense Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Toaster/>
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
